apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: tracing
  labels:
    app.kubernetes.io/part-of: jaeger
spec:
  ingress:
    enabled: false
  strategy: allInOne
  allInOne:
    image: docker.nexus.aetnadigital.net/jaegertracing/all-in-one:1.21.0
  storage:
    type: elasticsearch
    options:
      es:
       server-urls: https://es-jaeger-stg.${CLUSTER_ENV}.${CLUSTER_DOMAIN}:443
    dependencies:
      enabled: true
      elasticsearchNodesWanOnly: true
